version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "poetry run yoyo apply --database 'postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}' && poetry run uvicorn reminders.main:app --host 0.0.0.0 --port ${PORT}"
